version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - backend

  adminer:
    image: michalhosna/adminer
    container_name: adminer
    restart: always
    environment:
      - ADMINER_DRIVER=pgsql
      - ADMINER_SERVER=postgres
      - ADMINER_USERNAME=${POSTGRES_USER}
      - ADMINER_DB=${POSTGRES_DB}
    ports:
      - "8080:8080"
    networks:
      - backend

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    expose:
      - "3001"
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - postgres
    networks:
      - backend
      - frontend

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/my-app/src
    depends_on:
     - back
    networks:
      - frontend


volumes:
  db:
    driver: local

networks:
  frontend:
    name: frontend
  backend:
    name: backend