version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - postgres
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - 3000:3000
    depends_on:
     - postgres
